### PR TITLE
New logo pushes

### PR DESCRIPTION
**Pull request by TheRealJoshi**

### CODE REVIEW

**Comment by TheRealJoshi** [comment]
Pushing

**Comment by shrey150** [comment]
Sizing of logos looks a little different, I think we should scale down Thatch to make everything else fit better

**Comment by iyasinn** [comment]
> Sizing of logos looks a little different, I think we should scale down Thatch to make everything else fit better

Yeah agreed, I'll try remedying this

**Review by iyasinn — APPROVED** [review]
LGTM

**Pull request merged**
